[package]
name = "mtime-from-exif"
version = "0.1.0"
authors = ["Jenda Kolena <jendakolena@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
failure = "0.1.6"
filetime = "0.2.8"
humantime = "1.3.0"
rayon = "1.2.1"
regex = "1.3.1"
rexif = "0.3.7"
walkdir = "~2"
